### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by lgg** [joshbuchea/awesome-app-landing-page#1]
Maybe add favicon.ico and favicon.png for iphones?

**Comment by yofu1234** [comment]
I ended up adding the favicon to the site myself using: http://www.favicon-generator.org/

**Comment by lgg** [comment]
@yofu1234 yes, there are a lot of tools for generating code for favicon. But in my opinion it's will be very cool just to replace icon, without adding/changing code.

**Comment by joshbuchea** [comment]
Apologies @littleguga, I planned to add the favicons but forgot about this issue. I'll get these added in short order. Not sure what I want to use for the default icon. Any suggestions?
