### ISSUE TITLE
icon is not showing

### ISSUE THREAD

**Issue by imattaullah** [joshbuchea/awesome-app-landing-page#14]
customization too difficult and  it try to change icon but not succeeded.

**Comment by joshbuchea** [comment]
I'm sorry to hear that someone is having difficulties using my project. I'd like to help if I can. Can you provide some additional information? If you can provide a link to your fork, I'd be happy take a look.

**Comment by imattaullah** [comment]
i try a lot to show icon on browser tab but unfortunately now working.

**Comment by joshbuchea** [comment]
Is your fork public? If so I can take a look.

**Comment by rjm-codes** [comment]
oof

**Comment by joshbuchea** [comment]
This issue has been stale for over a month. I'm going to go ahead and close. I'd like to help and would be more than happy to take a look if you can provide the repo or website url.
