### ISSUE TITLE
Site not working, Github says "Your site is published" but when I go to the site, it says 404

### ISSUE THREAD

**Issue by yofu1234** [joshbuchea/awesome-app-landing-page#5]
So I followed the instructions but the site still not up. Github says "Your site is published at https://yofu1234.github.io/Feedshare-app" but when I go there, it says 404 there isn't a GitHub Pages site here. I have waited 10 minutes, used different browsers,  and its still not working.

**Comment by yofu1234** [comment]
Nvrm, fixed.

**Comment by joshbuchea** [comment]
@yofu1234 great! Not sure what the issue was, but any chance there is room for improvement in the documentation to make things clearer?

**Comment by yofu1234** [comment]
I had typed in https://yofu1234.github.io/Feedshare_app instead of https://yofu1234.github.io/Feedshare-app and didn't realize. Its a stupid mistake really.

**Comment by joshbuchea** [comment]
@yofu1234 ok glad you got it working 😊 Please let me know if you have any suggestions for improvements in the future. Have a great weekend!

**Comment by joshbuchea** [comment]
@yofu1234 I'm adding a section to the README that lists websites using this project. Would you mind if I added http://feedshare.org/ to the list?

**Comment by yofu1234** [comment]
Go ahead! :D

**Comment by joshbuchea** [comment]
Added :boom:

**Comment by yofu1234** [comment]
I'm new to github. When you change something on https://github.com/joshbuchea/awesome-app-landing-page/ does it automatically update mine too or do I have to fork it again somehow?

**Comment by joshbuchea** [comment]
@yofu1234 no, changes made to the project will not automatically update in your fork. If you'd like to pull in changes to your fork, you'll need to sync your fork:
- [Syncing a fork](https://help.github.com/articles/syncing-a-fork/)
- [Updating a fork directly from GitHub](http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/)

Just realized I should probably add the instructions for this to the README at some point.
