### ISSUE TITLE
quick suggestion: increase 'App Store' and 'Google Play' button sizes

### ISSUE THREAD

**Issue by yofu1234** [joshbuchea/awesome-app-landing-page#8]
quick suggestion: increase 'App Store' and 'Google Play' button sizes when viewing from mobile to increase conversion rates. Right now the two buttons are really small and often overlooked. The entire point of a landing page is to increase conversion rates. Having two small buttons really hurts it. The buttons should be big and have width that span almost the entire screen.

**Comment by joshbuchea** [comment]
The buttons don't seem that small to me. Point taken regarding conversion being the top priority though. Thanks for the suggestion @yofu1234!
